name: Node.js CI

# TODO: Remove vue when merged into main
on:
  push:
    branches:
      - main
      - vue

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd frontend
          npm ci
          npm run build
          mkdir ../server/built
          mv dist ../server/built/public
      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.nush.app
          repository: nush-link
          tags: latest
